name: Gerar APK Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v4

    - name: Configurar o Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Adicionar Chave da API do Gemini
      run: echo "apiKey=${{ secrets.gemini_api_key }}" > local.properties

    - name: Dar permissão ao Gradle
      run: chmod +x ./gradlew

    - name: Construir Tudo (App e Biblioteca)
      run: ./gradlew build assembleDebug

    - name: Cacada aos arquivos gerados
      run: |
        mkdir -p arquivos-gerados
        find . -name "*.apk" -exec cp {} arquivos-gerados/ \;
        find . -name "*.aar" -exec cp {} arquivos-gerados/ \;

    - name: Salvar os arquivos para Download
      uses: actions/upload-artifact@v4
      with:
        name: App-Gemini-Pronto
        path: arquivos-gerados/
